#include "initrd.h"
#include "vfs.h"
#include "../mm/heap.h"
#include "../utils/std.h"
#include "../hal/video/early_term.h"

// External VFS setter
extern "C" void vfs_set_root(VFSNode* root);

// Embedded MPK data (generated by bin2h.py, defined in desktop_mpk.cpp)
// Embedded MPK data (Legacy - Removed in favor of Dynamic InitRD)
// Apps are now loaded from initrd.img via UEFI Bootloader.


namespace InitRD {
    static VFSNode* root = nullptr;
    
    // Helper: Create a file node
    static VFSNode* CreateFileNode(const char* name, const char* content) {
        VFSNode* node = (VFSNode*)kmalloc(sizeof(VFSNode));
        if (!node) return nullptr;
        
        kmemset(node, 0, sizeof(VFSNode));
        
        // Copy name
        int i = 0;
        while (name[i] && i < 63) {
            node->name[i] = name[i];
            i++;
        }
        node->name[i] = 0;
        
        node->type = NodeType::FILE;
        
        // Copy content if provided
        if (content) {
            node->size = kstrlen(content);
            node->data = (uint8_t*)kmalloc(node->size + 1);
            if (node->data) {
                kmemcpy(node->data, content, node->size + 1);
            }
        } else {
            node->size = 0;
            node->data = nullptr;
        }
        
        return node;
    }
    
    // Helper: Create directory node
    static VFSNode* CreateDirNode(const char* name) {
        VFSNode* node = (VFSNode*)kmalloc(sizeof(VFSNode));
        if (!node) return nullptr;
        
        kmemset(node, 0, sizeof(VFSNode));
        
        // Copy name
        int i = 0;
        while (name[i] && i < 63) {
            node->name[i] = name[i];
            i++;
        }
        node->name[i] = 0;
        
        node->type = NodeType::DIRECTORY;
        node->size = 0;
        node->data = nullptr;
        
        return node;
    }
    
    // Helper: Add child to directory
    static void AddChild(VFSNode* parent, VFSNode* child) {
        if (!parent || !child) return;
        child->parent = parent;
        child->nextSibling = parent->firstChild;
        parent->firstChild = child;
    }

    // TAR Header Standard
    struct TarHeader {
        char name[100];
        char mode[8];
        char uid[8];
        char gid[8];
        char size[12];
        char mtime[12];
        char chksum[8];
        char typeflag;
        char linkname[100];
        char magic[6];
        char version[2];
        char uname[32];
        char gname[32];
        char devmajor[8];
        char devminor[8];
        char prefix[155];
        char pad[12];
    };

    static uint64_t OctalToDec(const char* str, int size) {
        uint64_t n = 0;
        const char* c = str;
        while (size-- > 0 && *c) {
            if (*c < '0' || *c > '7') break;
            n = (n * 8) + (*c - '0');
            c++;
        }
        return n;
    }

    // Helper: Create binary file from memory (NO COPY - uses direct pointer)
    static VFSNode* CreateTarFileNode(const char* name, const uint8_t* data, uint32_t size) {
        VFSNode* node = (VFSNode*)kmalloc(sizeof(VFSNode));
        if (!node) return nullptr;
        kmemset(node, 0, sizeof(VFSNode));
        
        // Copy name
        int i = 0;
        while (name[i] && i < 63) { node->name[i] = name[i]; i++; }
        node->name[i] = 0;
        
        node->type = NodeType::FILE;
        node->size = size;
        node->data = (uint8_t*)data;
        
        return node;
    }
    
    void Init(uint64_t initrdAddr, uint64_t initrdSize) {

        // Create root directory
        root = CreateDirNode("/");
        if (!root) {
            EarlyTerm::Print("[InitRD] ERROR: Cannot allocate root!\n");
            return;
        }
        
        // Create /etc directory for config files
        VFSNode* etcDir = CreateDirNode("etc");
        if (etcDir) AddChild(root, etcDir);
        
        // Create /initrd directory
        VFSNode* initDir = CreateDirNode("initrd");
        if (initDir) AddChild(root, initDir);

        VFSNode* bootcfg = CreateFileNode("boot.cfg", "showlogo=1\nverbose=1\n");
        if (bootcfg && etcDir) AddChild(etcDir, bootcfg);
        
        // Parse TAR if present
        if (initrdAddr != 0 && initrdSize > 0) {
            EarlyTerm::Print("[InitRD] Parsing TAR at ");
            EarlyTerm::PrintHex(initrdAddr);
            EarlyTerm::Print("\n");

            uint8_t* ptr = (uint8_t*)initrdAddr;
            uint8_t* end = ptr + initrdSize;

            while (ptr < end) {
                TarHeader* header = (TarHeader*)ptr;
                
                // Check for empty block (end of archive)
                if (header->name[0] == 0) break;

                uint64_t fileSize = OctalToDec(header->size, 11);
                
                // We only handle standard files (typeflag '0' or '\0')
                if (header->typeflag == '0' || header->typeflag == 0) {
                    // Create Node
                    // Simplify name (remove path if exists, we put everything in /initrd/ for now?)
                    // Or respect paths.
                    // For safety in this phase, let's put everything in /initrd/ + basename
                    
                    const char* fname = header->name;
                    // Find last slash
                    int len = kstrlen(fname);
                    for(int i=len-1; i>=0; i--) {
                        if (fname[i] == '/') { fname = &fname[i+1]; break; }
                    }

                    // Only map .mpk files
                    // if (kstrstr(fname, ".mpk")) ... nah map everything
                    
                    VFSNode* node = CreateTarFileNode(fname, ptr + 512, fileSize);
                    if (node && initDir) {
                        AddChild(initDir, node);
                        EarlyTerm::Print("  Loaded: ");
                        EarlyTerm::Print(fname);
                        EarlyTerm::Print("\n");
                    }
                }
                
                // Move to next header
                // Size rounded up to 512 bytes + header size
                uint64_t alignedSize = (fileSize + 511) & ~511;
                ptr += 512 + alignedSize;
            }
        } else {
            EarlyTerm::Print("[InitRD] Warning: No InitRD image found.\n");
        }
        
        // Set VFS root
        vfs_set_root(root);
        
        EarlyTerm::Print("[InitRD] Mounted at / with ");
        uint32_t count = 0;
        VFSNode* child = root->firstChild;
        while (child) { count++; child = child->nextSibling; }
        EarlyTerm::PrintDec(count);
        EarlyTerm::Print(" files.\n");
    }
    
    VFSNode* GetRoot() {
        return root;
    }
}
