#include "initrd.h"
#include "vfs.h"
#include "../mm/heap.h"
#include "../utils/std.h"
#include "../hal/video/early_term.h"

// External VFS setter
extern "C" void vfs_set_root(VFSNode* root);

// Embedded MPK data (generated by bin2h.py, defined in desktop_mpk.cpp)
#ifdef EMBED_DESKTOP
extern const uint8_t desktop_mpk_data[];
extern const uint32_t desktop_mpk_size;
#endif


namespace InitRD {
    static VFSNode* root = nullptr;
    
    // Helper: Create a file node
    static VFSNode* CreateFileNode(const char* name, const char* content) {
        VFSNode* node = (VFSNode*)kmalloc(sizeof(VFSNode));
        if (!node) return nullptr;
        
        kmemset(node, 0, sizeof(VFSNode));
        
        // Copy name
        int i = 0;
        while (name[i] && i < 63) {
            node->name[i] = name[i];
            i++;
        }
        node->name[i] = 0;
        
        node->type = NodeType::FILE;
        
        // Copy content if provided
        if (content) {
            node->size = kstrlen(content);
            node->data = (uint8_t*)kmalloc(node->size + 1);
            if (node->data) {
                kmemcpy(node->data, content, node->size + 1);
            }
        } else {
            node->size = 0;
            node->data = nullptr;
        }
        
        return node;
    }
    
    // Helper: Create directory node
    static VFSNode* CreateDirNode(const char* name) {
        VFSNode* node = (VFSNode*)kmalloc(sizeof(VFSNode));
        if (!node) return nullptr;
        
        kmemset(node, 0, sizeof(VFSNode));
        
        // Copy name
        int i = 0;
        while (name[i] && i < 63) {
            node->name[i] = name[i];
            i++;
        }
        node->name[i] = 0;
        
        node->type = NodeType::DIRECTORY;
        node->size = 0;
        node->data = nullptr;
        
        return node;
    }
    
    // Helper: Add child to directory
    static void AddChild(VFSNode* parent, VFSNode* child) {
        if (!parent || !child) return;
        child->parent = parent;
        child->nextSibling = parent->firstChild;
        parent->firstChild = child;
    }

    // Helper: Create binary file from memory (NO COPY - uses direct pointer)
    // CRITICAL: For embedded data, we point directly to avoid heap exhaustion.
    static VFSNode* CreateBinaryNode(const char* name, const uint8_t* data, uint32_t size) {
        VFSNode* node = (VFSNode*)kmalloc(sizeof(VFSNode));
        if (!node) return nullptr;
        kmemset(node, 0, sizeof(VFSNode));
        
        // Copy name
        int i = 0;
        while (name[i] && i < 63) { node->name[i] = name[i]; i++; }
        node->name[i] = 0;
        
        node->type = NodeType::FILE;
        node->size = size;
        
        // DIRECT POINTER - NO COPY
        // The data is already in kernel .rodata section, safe to reference.
        node->data = (uint8_t*)data;
        
        return node;
    }
    
    void Init() {

        // Create root directory
        root = CreateDirNode("/");
        if (!root) {
            EarlyTerm::Print("[InitRD] ERROR: Cannot allocate root!\n");
            return;
        }
        
        // Create /etc directory for config files
        VFSNode* etcDir = CreateDirNode("etc");
        if (etcDir) AddChild(root, etcDir);
        
        // Create /initrd directory (optional, but requested by user path /initrd/desktop.mpk)
        // User path: /initrd/desktop.mpk
        // So we should mount creating this directory or mount root AS /initrd? 
        // Current shell "ls" shows root. If I put desktop.mpk in /initrd/ folder, it works.
        VFSNode* initDir = CreateDirNode("initrd");
        if (initDir) AddChild(root, initDir);

        // ... Config ...
        VFSNode* bootcfg = CreateFileNode("boot.cfg", "showlogo=1\nverbose=1\n");
        if (bootcfg && etcDir) AddChild(etcDir, bootcfg);
        
        // ... Embed Desktop MPK ...
        // We use a weak symbol or check if defined to avoid build break if not ready
        // But better to enforce it via Makefile.
        #ifdef EMBED_DESKTOP
            // Note: Symbols defined at global scope in desktop_mpk.cpp
            VFSNode* mpk = CreateBinaryNode("desktop.mpk", ::desktop_mpk_data, ::desktop_mpk_size);

            if (mpk && initDir) {
                AddChild(initDir, mpk);
                EarlyTerm::Print("[InitRD] Embedded /initrd/desktop.mpk\n");
            }
        #endif

        if (bootcfg && etcDir) AddChild(etcDir, bootcfg); // Duplicate? Removed in overwrite.
        
        // Set VFS root
        vfs_set_root(root);
        
        // ...

        
        // Set VFS root
        vfs_set_root(root);
        
        EarlyTerm::Print("[InitRD] Mounted at / with ");
        uint32_t count = 0;
        VFSNode* child = root->firstChild;
        while (child) { count++; child = child->nextSibling; }
        EarlyTerm::PrintDec(count);
        EarlyTerm::Print(" files.\n");
    }
    
    VFSNode* GetRoot() {
        return root;
    }
}
