#pragma once
#include <stdint.h>
#include <stddef.h>

// Auto-generated by tools/mpk_pack.py
// Offsets are relative to the assets block base pointer passed to main(void* assets_ptr).
// This matches the current MPK1 convention: header + code + assets (raw bytes).

#define calculator_MPK_ASSET_COUNT 0

static inline const uint8_t* mpk_asset_ptr(const void* assets_base, uint32_t offset)
{
    return ((const uint8_t*)assets_base) + (size_t)offset;
}

