#pragma once
#include <stdint.h>
#include <stddef.h>

// Auto-generated by tools/mpk_pack.py
// Offsets are relative to the assets block base pointer passed to main(void* assets_ptr).
// This matches the current MPK1 convention: header + code + assets (raw bytes).

#define desktop_MPK_ASSET_COUNT 2

#define desktop_MPK_ASSET_WALLPAPER_OFFSET 152
#define desktop_MPK_ASSET_WALLPAPER_SIZE   3145728
#define desktop_MPK_ASSET_WALLPAPER_PATH   "assets/wallpaper.raw"

#define desktop_MPK_ASSET_ICON_OFFSET 3145880
#define desktop_MPK_ASSET_ICON_SIZE   16384
#define desktop_MPK_ASSET_ICON_PATH   "assets/icon.raw"

static inline const uint8_t* mpk_asset_ptr(const void* assets_base, uint32_t offset)
{
    return ((const uint8_t*)assets_base) + (size_t)offset;
}

