#!/usr/bin/env python3
import sys
import struct
import os

# Morphic Package Format (.mpk)
# Header Structure (Little Endian):
# Magic: 4 bytes "MPK1"
# Manifest Offset: 4 bytes (0 = no manifest; else typically 64)
# Code Offset: 4 bytes
# Code Size: 4 bytes
# Assets Offset: 4 bytes
# Assets Size: 4 bytes
# ... (header may be padded; current packer uses 64 bytes) ...

# Header padding (bytes 24..63) is reserved for forward-compat.
# Convention used by this packer:
#   - uint32_t total_size at offset 24 (optional; 0 means "not set")


def _sanitize_define_name(path: str) -> str:
    base = os.path.basename(path)
    name, _ext = os.path.splitext(base)
    out = []
    for ch in name:
        if ('a' <= ch <= 'z') or ('A' <= ch <= 'Z') or ('0' <= ch <= '9'):
            out.append(ch.upper())
        else:
            out.append('_')
    s = ''.join(out)
    while '__' in s:
        s = s.replace('__', '_')
    return s.strip('_') or 'ASSET'


def _pad_to(data: bytearray, align: int) -> None:
    if align <= 1:
        return
    pad = (-len(data)) % align
    if pad:
        data.extend(b'\x00' * pad)


def _align_up(value: int, align: int) -> int:
    if align <= 1:
        return value
    return (value + (align - 1)) & ~(align - 1)


def _write_assets_header(header_path: str, prefix: str, assets: list[dict]) -> None:
    # assets entries: {"define": str, "path": str, "offset": int, "size": int}
    guard = f"{prefix}_MPK_ASSETS_H".upper()
    lines: list[str] = []
    lines.append("#pragma once")
    lines.append("#include <stdint.h>")
    lines.append("#include <stddef.h>")
    lines.append("")
    lines.append("// Auto-generated by tools/mpk_pack.py")
    lines.append("// Offsets are relative to the assets block base pointer passed to main(void* assets_ptr).")
    lines.append("// This matches the current MPK1 convention: header + code + assets (raw bytes).")
    lines.append("")
    lines.append(f"#define {prefix}_MPK_ASSET_COUNT {len(assets)}")
    lines.append("")

    for a in assets:
        d = a["define"]
        lines.append(f"#define {prefix}_MPK_ASSET_{d}_OFFSET {a['offset']}")
        lines.append(f"#define {prefix}_MPK_ASSET_{d}_SIZE   {a['size']}")
        lines.append(f"#define {prefix}_MPK_ASSET_{d}_PATH   \"{a['path']}\"")
        lines.append("")

    lines.append("static inline const uint8_t* mpk_asset_ptr(const void* assets_base, uint32_t offset)")
    lines.append("{")
    lines.append("    return ((const uint8_t*)assets_base) + (size_t)offset;")
    lines.append("}")
    lines.append("")

    os.makedirs(os.path.dirname(header_path) or '.', exist_ok=True)
    with open(header_path, 'w', encoding='utf-8') as f:
        f.write("\n".join(lines) + "\n")


def create_mpk(binary_path, assets_paths, output_path, *, manifest_path=None, gen_header=None, header_prefix="MPK", assets_align=1, code_align=16):
    HEADER_SIZE = 64
    MAGIC = b'MPK1'

    # Read Binary
    try:
        with open(binary_path, 'rb') as f:
            code_data = f.read()
    except FileNotFoundError:
        print(f"Error: Binary file {binary_path} not found.")
        return 1

    if not code_data:
        print(f"Error: Binary file {binary_path} is empty (code_size=0).")
        return 2

    # Optional manifest block (raw bytes; may be text or binary)
    manifest_data = b""
    if manifest_path:
        try:
            with open(manifest_path, 'rb') as f:
                manifest_data = f.read()
        except FileNotFoundError:
            print(f"Error: Manifest file {manifest_path} not found.")
            return 3

    # Read Assets (raw concatenation; optional alignment/padding)
    # NEW: Prepend an Asset Table (Index) to the assets blob.
    # Table Header: Magic(4) + Count(4)
    # Entry: Name(64) + Offset(4) + Size(4)
    
    assets_blob = bytearray()
    assets_index: list[dict] = []
    used_names: dict[str, int] = {}

    # Calculate table size first
    # Header: 8 bytes
    # Entry: 64 + 4 + 4 = 72 bytes
    TABLE_HEADER_SIZE = 8
    ENTRY_SIZE = 72
    table_size = TABLE_HEADER_SIZE + (len(assets_paths) * ENTRY_SIZE)
    
    # Align table size to assets_align if needed (though usually table is at offset 0 of assets block)
    # We will write the table into assets_blob first.
    assets_blob.extend(b'\x00' * table_size)
    
    current_offset = table_size

    for i, asset_path in enumerate(assets_paths):
        try:
            with open(asset_path, 'rb') as f:
                data = f.read()
        except FileNotFoundError:
            print(f"Warning: Asset {asset_path} not found.")
            continue

        # Align start of asset data relative to assets block start
        pad = 0
        if assets_align > 1:
            misalign = (current_offset) % assets_align
            if misalign != 0:
                pad = assets_align - misalign
                assets_blob.extend(b'\x00' * pad)
                current_offset += pad

        assets_blob.extend(data)
        size = len(data)
        
        # Store entry info
        base_name = os.path.basename(asset_path)
        
        # For C header define
        define = _sanitize_define_name(asset_path)
        if define in used_names:
            used_names[define] += 1
            define = f"{define}_{used_names[define]}"
        else:
            used_names[define] = 0

        assets_index.append({
            "define": define,
            "path": asset_path,
            "name": base_name,
            "offset": current_offset,
            "size": size,
        })
        
        current_offset += size

    # Now write the table at the beginning of assets_blob
    # Magic: ASST (0x54535341 little endian)
    struct.pack_into('<4sI', assets_blob, 0, b'ASST', len(assets_index))
    
    idx_offset = 8
    for entry in assets_index:
        # Name (64 bytes, null padded)
        name_bytes = entry["name"].encode('utf-8')[:63]
        struct.pack_into('<64sII', assets_blob, idx_offset, name_bytes, entry["offset"], entry["size"])
        idx_offset += 72

    manifest_off = 0
    if manifest_data:
        manifest_off = HEADER_SIZE

    code_offset = _align_up(HEADER_SIZE + len(manifest_data), code_align)
    code_size = len(code_data)
    assets_offset = code_offset + code_size
    assets_size = len(assets_blob)

    total_size = assets_offset + assets_size

    header = struct.pack(
        '<4sIIIII',
        MAGIC,
        manifest_off,
        code_offset,
        code_size,
        assets_offset,
        assets_size,
    )

    # Pad header to 64 bytes (forward-compat room) and store total_size at offset 24.
    # This does not change the first 24 bytes layout (loader reads that today).
    header = bytearray(header)
    header.extend(b'\x00' * (HEADER_SIZE - len(header)))
    header[24:28] = struct.pack('<I', total_size)
    header = bytes(header)

    print(f"Creating Package: {output_path}")
    if manifest_data:
        print(f"  Manifest: {manifest_path} ({len(manifest_data)} bytes)")
    print(f"  Code Size: {code_size} bytes")
    print(f"  Assets Size: {assets_size} bytes")
    print(f"  Total Size: {total_size} bytes")
    if assets_align and assets_align > 1:
        print(f"  Assets Align: {assets_align} bytes")
    if code_align and code_align > 1:
        print(f"  Code Align: {code_align} bytes")
    if gen_header:
        print(f"  Generating Assets Header: {gen_header} (prefix={header_prefix})")

    with open(output_path, 'wb') as f:
        f.write(header)
        if manifest_data:
            f.write(manifest_data)
            pad_len = code_offset - (HEADER_SIZE + len(manifest_data))
            if pad_len:
                f.write(b'\x00' * pad_len)
        f.write(code_data)
        f.write(assets_blob)

    if gen_header:
        _write_assets_header(gen_header, header_prefix, assets_index)

    print("Done.")
    return 0


def _parse_legacy_args(argv: list[str]):
    # Backwards compatible parsing:
    #   mpk_pack.py <output.mpk> <binary.bin> [asset1] [asset2] ...
    #              [--manifest path] [--gen-header path] [--prefix NAME] [--align N] [--code-align N]
    if len(argv) < 3:
        return None

    output = argv[1]
    binary = argv[2]
    assets: list[str] = []
    manifest = None
    gen_header = None
    prefix = "MPK"
    align = 1
    code_align = 16

    i = 3
    while i < len(argv):
        a = argv[i]
        if a == "--gen-header" and (i + 1) < len(argv):
            gen_header = argv[i + 1]
            i += 2
            continue
        if a == "--manifest" and (i + 1) < len(argv):
            manifest = argv[i + 1]
            i += 2
            continue
        if a == "--prefix" and (i + 1) < len(argv):
            prefix = argv[i + 1]
            i += 2
            continue
        if a == "--align" and (i + 1) < len(argv):
            try:
                align = int(argv[i + 1], 0)
            except ValueError:
                print(f"Error: invalid --align value: {argv[i + 1]}")
                return None
            i += 2
            continue
        if a == "--code-align" and (i + 1) < len(argv):
            try:
                code_align = int(argv[i + 1], 0)
            except ValueError:
                print(f"Error: invalid --code-align value: {argv[i + 1]}")
                return None
            i += 2
            continue

        assets.append(a)
        i += 1

    return output, binary, assets, manifest, gen_header, prefix, align, code_align


if __name__ == "__main__":
    parsed = _parse_legacy_args(sys.argv)
    if not parsed:
        print("Usage: ./mpk_pack.py <output.mpk> <binary.bin> [asset1] [asset2] ...")
        print("Optional flags:")
        print("  --manifest <path>      Include a manifest block after the header")
        print("  --gen-header <path>   Emit a C header with asset offsets/sizes")
        print("  --prefix <NAME>       Macro prefix for generated header (default: MPK)")
        print("  --align <N>           Pad each asset start to N-byte alignment (default: 1)")
        print("  --code-align <N>      Align code start to N bytes (default: 16)")
        sys.exit(1)

    output, binary, assets, manifest, gen_header, prefix, align, code_align = parsed
    rc = create_mpk(
        binary,
        assets,
        output,
        manifest_path=manifest,
        gen_header=gen_header,
        header_prefix=prefix,
        assets_align=align,
        code_align=code_align,
    )
    sys.exit(rc)
